### ISSUE TITLE
Python 2 vs Python 3 detection in print statements and bug due to completely empty files

### ISSUE THREAD

**Issue by fredericoschardong** [abarker/camel-snake-pep8#2]
Not working for the following python3 code:

` def throwAllocationErrorAndExit(self):

        print(
            "The parameters used and memory allocation cofiguration resulted in subsets with no elements, can't continue.", file=sys.stderr,
        )
        os.popen("rm -Rf " + self.folder)`

I get:
`
Traceback (most recent call last):
  File "camel_snake_pep8.py", line 848, in <module>
    main()
  File "camel_snake_pep8.py", line 793, in main
    rope.base.libutils.analyze_modules(project) # Analyze all the modules.
  File "/usr/local/lib/python2.7/dist-packages/rope/base/libutils.py", line 81, in analyze_modules
    analyze_module(project, resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/libutils.py", line 69, in analyze_module
    project.pycore.analyze_module(resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pycore.py", line 210, in analyze_module
    self, pymodule, should_analyze, search_subscopes, followed_calls)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 16, in analyze_module
    search_subscopes, followed_calls)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 24, in _analyze_node
    search_subscopes, followed_calls)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 24, in _analyze_node
    search_subscopes, followed_calls)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 117, in _Assign
    rope.base.ast.walk(child, self)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/oi/soa.py", line 58, in _Call
    primary, pyname = evaluate.eval_node2(self.scope, node.func)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/ast.py", line 39, in walk
    return method(node)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/evaluate.py", line 158, in _Attribute
    self.result = pyname.get_object()[node.attr]
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 28, in __getitem__
    return self.get_attribute(key)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 204, in get_attribute
    if name in self._get_concluded_attributes():
  File "/usr/local/lib/python2.7/dist-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjects.py", line 191, in _get_concluded_attributes
    self.concluded_attributes.set(self._create_concluded_attributes())
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 135, in _create_concluded_attributes
    for base in reversed(self.get_superclasses()):
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 127, in get_superclasses
    self._superclasses.set(self._get_bases())
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 145, in _get_bases
    base.get_object().get_type() == \
  File "/usr/local/lib/python2.7/dist-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pynames.py", line 160, in get_object
    return self._get_imported_pyname().get_object()
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pynames.py", line 151, in _get_imported_pyname
    result = self.imported_module.get_object()[self.imported_name]
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pynames.py", line 132, in get_object
    if self._get_pymodule() is None:
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pynames.py", line 121, in _get_pymodule
    self.module_name, self._current_folder())
  File "/usr/local/lib/python2.7/dist-packages/rope/base/project.py", line 60, in get_module
    return self.pycore.resource_to_pyobject(module)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pycore.py", line 142, in resource_to_pyobject
    return self.module_cache.get_pymodule(resource, force_errors)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pycore.py", line 255, in get_pymodule
    force_errors=force_errors)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 162, in __init__
    source, node = self._init_source(pycore, source, resource)
  File "/usr/local/lib/python2.7/dist-packages/rope/base/pyobjectsdef.py", line 191, in _init_source
    raise exceptions.ModuleSyntaxError(filename, e.lineno, e.msg)
rope.base.exceptions.ModuleSyntaxError: Syntax error in file <src/vanillas/proto_vanilla.py> line <246>: invalid syntax
`

Line 246 is ` "The parameters used and memory allocation cofiguration resulted in subsets with no elements, can't continue.", file=sys.stderr,`

**Comment by abarker** [comment]
The problem isn't that it is a multi-line print but that the `print` statement is being treated by Rope as Python 2 vs. Python 3.

Rope has been updating their Python 3 handling since the program was written, and can now run in Python 3.  I've updated the code and the README.  The new rule is to run `camel_snake_pep8.py` with the same version of Python (2 or 3) that the code being converted is written in.

Try running the new version on the code, using the Python 3 interpreter.

**Comment by fredericoschardong** [comment]
It worked! It would be nice if you could add a recursive argument regarding the files to be converted. I had to run it on each folder (probably could have used `*/*.py` and `*/*/*.py`, but still would be more than one execution). Furthermore, for some runs I got this error, despite everything being converted just fine:

Doing post-processing name analysis on all modules.

`Traceback (most recent call last):
  File "camel_snake_pep8.py", line 857, in <module>
    main()
  File "camel_snake_pep8.py", line 812, in main
    possible_changes = rope_iterate_worder(filename, assigned_vars=True)
  File "camel_snake_pep8.py", line 472, in rope_iterate_worder
    elif (w.is_assigned_here(offset) or w.is_assigned_in_a_tuple_assignment(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 111, in is_assigned_in_a_tuple_assignment
    return self.code_finder.is_assigned_in_a_tuple_assignment(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 512, in is_assigned_in_a_tuple_assignment
    primary_start = self._find_primary_start(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 219, in _find_primary_start
    if self.code[offset] != '.':
IndexError: string index out of range`

During handling of the above exception, another exception occurred:

`Traceback (most recent call last):
  File "camel_snake_pep8.py", line 862, in <module>
    analyze_names_in_final_state([os.path.realpath(f) for f in fname_list])
  File "camel_snake_pep8.py", line 148, in analyze_names_in_final_state
    save_set_of_all_names_in_module(module_realpath, save_dict=final_names_sets_dict)
  File "camel_snake_pep8.py", line 77, in save_set_of_all_names_in_module
    names_in_module = rope_iterate_worder(file_realpath, unfiltered=True)
  File "camel_snake_pep8.py", line 472, in rope_iterate_worder
    elif (w.is_assigned_here(offset) or w.is_assigned_in_a_tuple_assignment(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 111, in is_assigned_in_a_tuple_assignment
    return self.code_finder.is_assigned_in_a_tuple_assignment(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 512, in is_assigned_in_a_tuple_assignment
    primary_start = self._find_primary_start(offset)
  File "/usr/local/lib/python3.7/dist-packages/rope/base/worder.py", line 219, in _find_primary_start
    if self.code[offset] != '.':
IndexError: string index out of range`

Unfortunately, I can not share the code in which the tool was used. Nonetheless, good work! Saved me a lot of time.

**Comment by abarker** [comment]
A recursive argument would be a nice addition.  As it is, you can pass the program all the `.py` files at once with a command like `python3 camel_snake_pep8.py proj_dir *.py */*.py */*/*.py` etc.

That exception in the final analysis seems to have been occurring due to empty source files (such as an empty `__init__.py` file).  None of my test cases had a completely empty file.  Should be fixed now.
