### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute '_fields' exception with Python3.8

### ISSUE THREAD

**Issue by ntouran** [abarker/camel-snake-pep8#4]
I tried running this on https://github.com/terrapower/armi as part of https://github.com/terrapower/armi/issues/112 but ran into the following exception. I'm using Python 3.8. 

Invocation was: `$ python camel_snake_pep8.py . *.py */*.py`

```
Traceback (most recent call last):
  File "camel_snake_pep8.py", line 857, in <module>
    main()
  File "camel_snake_pep8.py", line 801, in main
    rope.base.libutils.analyze_modules(project) # Analyze all the modules.
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/libutils.py", line 82, in analyze_modules
    analyze_module(project, resource)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/libutils.py", line 70, in analyze_module
    project.pycore.analyze_module(resource)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pycore.py", line 209, in analyze_module
    rope.base.oi.soa.analyze_module(
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 15, in analyze_module
    _analyze_node(pycore, pymodule, should_analyze,
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 42, in walk
    walk(child, walker)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 76, in _Call
    self._call(pyfunction, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 93, in _call
    self.follow(pyfunction)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 31, in _follow
    _analyze_node(pycore, pyfunction, return_true,
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 42, in walk
    walk(child, walker)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 117, in _Assign
    rope.base.ast.walk(child, self)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 76, in _Call
    self._call(pyfunction, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soa.py", line 88, in _call
    pyfunction, args.get_arguments(pyfunction.get_param_names()))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/arguments.py", line 20, in get_arguments
    for pyname in self.get_pynames(parameters):
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/arguments.py", line 33, in get_pynames
    result[index] = self._evaluate(arg)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/arguments.py", line 41, in _evaluate
    return rope.base.evaluate.eval_node(self.scope, ast_node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 189, in _Call
    pyobject=_get_returned(pyfunction))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 73, in get_returned_object
    return self.returned.get(args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 45, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 25, in infer_returned_object
    result = _infer_returned(pyfunction, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 111, in _infer_returned
    resulting_pyname = evaluate.eval_node(scope, returned_node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 163, in _Call
    primary, pyobject = self._get_primary_and_object_for_node(node.func)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 292, in _get_primary_and_object_for_node
    primary, pyname = eval_node2(self.scope, stmt)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 152, in _Attribute
    pyname = eval_node(self.scope, node.value)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 300, in _Subscript
    self._call_function(node.value, '__getitem__',
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 312, in _call_function
    pyobject = pyname.get_object()
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 71, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 142, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 175, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 189, in _Call
    pyobject=_get_returned(pyfunction))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 73, in get_returned_object
    return self.returned.get(args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 45, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 25, in infer_returned_object
    result = _infer_returned(pyfunction, args)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 114, in _infer_returned
    pyobject = resulting_pyname.get_object()
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynamesdef.py", line 22, in get_object
    return self.pyobject.get()
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/pynamesdef.py", line 19, in _get_inferred
    return rope.base.oi.soi.infer_assigned_object(self)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 71, in infer_assigned_object
    result = _infer_assignment(assignment, pyname.module)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 142, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/oi/soi.py", line 175, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 236, in _Dict
    keys = self._get_object_for_node(node.keys[0])
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 285, in _get_object_for_node
    pyname = eval_node(self.scope, stmt)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 41, in walk
    for child in get_child_nodes(node):
  File "/opt/venvs/armi/lib/python3.8/site-packages/rope/base/ast.py", line 49, in get_child_nodes
    if node._fields is not None:
AttributeError: 'NoneType' object has no attribute '_fields'
```

**Comment by abarker** [comment]
Is it raising this exception first thing, before it does any replacements? I cloned that repo and tried running the program on it using Python 3.8. I didn't go through the whole large project, but it started off the way it's supposed to.  I assume you ran the command from the `armi/armi` directory.  Have you tried upgrading to the most recent dependencies, especially Rope?
