### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'lineno'

### ISSUE THREAD

**Issue by gcaria** [abarker/camel-snake-pep8#5]
Hi, this is the output that I get from the main script
( just after having run `pip install rope colorama --upgrade` and with Python 3.8.3. )

```
Converting these files:

    [list of files]

Hit enter to begin the refactoring...

Analyzing all the modules in the project, may be slow...
==============================================================================
==============================================================================
===== Doing post-processing name analysis on all modules. ====================
==============================================================================
==============================================================================

Any warnings below are only for potential problems.  Most will probably
not be problems.  No scoping information is taken into account in this
analysis.

------------------------------------------------------------------------------
----- User-rejected change information. --------------------------------------
------------------------------------------------------------------------------

------------------------------------------------------------------------------
----- Rope-rejected change information. --------------------------------------
------------------------------------------------------------------------------

------------------------------------------------------------------------------
----- Accepted change information. -------------------------------------------
------------------------------------------------------------------------------

Traceback (most recent call last):
  File "../camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 857, in <module>
    main()
  File "../camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 801, in main
    rope.base.libutils.analyze_modules(project) # Analyze all the modules.
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/libutils.py", line 82, in analyze_modules
    analyze_module(project, resource)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/libutils.py", line 70, in analyze_module
    project.pycore.analyze_module(resource)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pycore.py", line 209, in analyze_module
    rope.base.oi.soa.analyze_module(
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 15, in analyze_module
    _analyze_node(pycore, pymodule, should_analyze,
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 23, in _analyze_node
    _analyze_node(pycore, scope.pyobject, should_analyze,
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 117, in _Assign
    rope.base.ast.walk(child, self)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 76, in _Call
    self._call(pyfunction, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 93, in _call
    self.follow(pyfunction)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 31, in _follow
    _analyze_node(pycore, pyfunction, return_true,
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 38, in _analyze_node
    rope.base.ast.walk(child, visitor)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 42, in walk
    walk(child, walker)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 42, in walk
    walk(child, walker)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 123, in _Assign
    self._evaluate_assign_value(node, nodes)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soa.py", line 130, in _evaluate_assign_value
    value = rope.base.oi.soi._infer_assignment(
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 142, in _infer_assignment
    result = _follow_pyname(assignment, pymodule)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 175, in _follow_pyname
    pyname = evaluate.eval_node(holding_scope, assign_node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 189, in _Call
    pyobject=_get_returned(pyfunction))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 73, in get_returned_object
    return self.returned.get(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 45, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 25, in infer_returned_object
    result = _infer_returned(pyfunction, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 111, in _infer_returned
    resulting_pyname = evaluate.eval_node(scope, returned_node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 189, in _Call
    pyobject=_get_returned(pyfunction))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 73, in get_returned_object
    return self.returned.get(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 45, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 22, in infer_returned_object
    result = object_info.get_exact_returned(pyfunction, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/objectinfo.py", line 90, in get_exact_returned
    path, key, self._args_to_textual(pyobject, args))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/objectinfo.py", line 96, in _args_to_textual
    arguments = args.get_arguments(parameters)[:len(parameters)]
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/arguments.py", line 20, in get_arguments
    for pyname in self.get_pynames(parameters):
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/arguments.py", line 33, in get_pynames
    result[index] = self._evaluate(arg)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/arguments.py", line 41, in _evaluate
    return rope.base.evaluate.eval_node(self.scope, ast_node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 42, in walk
    walk(child, walker)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 175, in _Call
    result = _get_returned(new_function)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 108, in get_returned_object
    return self.function(_CallContext(self.argnames, args))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 440, in _new_tuple
    return _create_builtin(args, get_tuple)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 722, in _create_builtin
    holding = _infer_sequence_for_pyname(passed)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 710, in _infer_sequence_for_pyname
    iter = obj.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 73, in get_returned_object
    return self.returned.get(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 29, in newfunc
    return func(self, *args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pynames.py", line 189, in get
    self.set(self.get_inferred(*args, **kwds))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pyobjectsdef.py", line 45, in _infer_returned
    return rope.base.oi.soi.infer_returned_object(self, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/utils/__init__.py", line 41, in newfunc
    return func(*args, **kwds)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 25, in infer_returned_object
    result = _infer_returned(pyfunction, args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/oi/soi.py", line 111, in _infer_returned
    resulting_pyname = evaluate.eval_node(scope, returned_node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 27, in eval_node
    return eval_node2(scope, node)[1]
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 32, in eval_node2
    ast.walk(node, evaluator)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/ast.py", line 40, in walk
    return method(node)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 189, in _Call
    pyobject=_get_returned(pyfunction))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/evaluate.py", line 170, in _get_returned
    return pyobject.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 108, in get_returned_object
    return self.function(_CallContext(self.argnames, args))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 787, in _iter_function
    holding = _infer_sequence_for_pyname(passed)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 710, in _infer_sequence_for_pyname
    iter = obj.get_returned_object(args)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 108, in get_returned_object
    return self.function(_CallContext(self.argnames, args))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 392, in _key_iter
    return get_iterator(self._key_get(context))
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 376, in _key_get
    item = self._item_get(context).get_type()
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 366, in _item_get
    item = context.get_per_name()
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 219, in get_per_name
    scope, name = self._get_scope_and_pyname(pyname)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/builtins.py", line 179, in _get_scope_and_pyname
    pymodule, lineno = pyname.get_definition_location()
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pynamesdef.py", line 27, in get_definition_location
    self.lineno = self.assignments[0].get_lineno()
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/pynames.py", line 69, in get_lineno
    return self.ast_node.lineno
AttributeError: 'NoneType' object has no attribute 'lineno'
```

**Comment by abarker** [comment]
This is probably related to issue https://github.com/abarker/camel-snake-pep8/issues/4, and may be due to the Rope bug https://github.com/python-rope/rope/issues/260.

I couldn't reproduce issue https://github.com/abarker/camel-snake-pep8/issues/4 after cloning the code that was being refactored there and running with Python 3.8.0.

For additional info, what OS are you running on?  Have you tried running the program with an older version of Python 3?

As a workaround, I've pushed an update which wraps the call to Rope's `analyze_modules` in a try block, catching `AttributeError` and just printing a warning if it is raised.  Calling `analyze_modules` is optional with Rope, but it is supposed to improve Rope's static analysis.

**Comment by gcaria** [comment]
This happens on Scientific Linux release 6.6 (Carbon) (unfortunately it's a work server so it's not a choice)
No, I haven't tried on an older version of Python 3.

Thanks I'll now try with the patch !

**Comment by gcaria** [comment]
I pulled the last version, and I know get:

```
Hit enter to begin the refactoring...

Analyzing all the modules in the project, may be slow...
Rope failed to analyze modules (possible Rope issue 260).
Proceeding without the analysis.
```

Is this something related to this issue ?

**Comment by abarker** [comment]
That's just the warning I added for when the call to  `analyze_modules` fails.  It should still run OK without that call.  Did it run correctly after the warning?

**Comment by gcaria** [comment]
It seems to be running correctly now.

By the way, is there a way to simply accept all changes at once without having to review each single one ?
I find that I accept the proposed change 95% of the time, so I'd happily change everything at the same time, and then go back and adapt that 5% that I don't like.

EDIT:

I've tried to run the script on a different directory and now I'm getting:

```
Hit enter to begin the refactoring...

Analyzing all the modules in the project, may be slow...
Finished the analysis.

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%% Python module name: jobs.groupMonths %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

==============================================================================
===== Changing variables assigned in the code. ===============================
==============================================================================

Unexpected error in calculating a rename from 'monthsGroup' to 'months_group' in file
   jobs/groupMonths.py
==============================================================================
==============================================================================
===== Doing post-processing name analysis on all modules. ====================
==============================================================================
==============================================================================

Any warnings below are only for potential problems.  Most will probably
not be problems.  No scoping information is taken into account in this
analysis.

------------------------------------------------------------------------------
----- User-rejected change information. --------------------------------------
------------------------------------------------------------------------------

------------------------------------------------------------------------------
----- Rope-rejected change information. --------------------------------------
------------------------------------------------------------------------------

------------------------------------------------------------------------------
----- Accepted change information. -------------------------------------------
------------------------------------------------------------------------------

Traceback (most recent call last):
  File "/home/gcaria/camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 862, in <module>
    main()
  File "/home/gcaria/camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 821, in main
    if not rope_rename_refactor(project, filename, possible_changes, docs=docs):
  File "/home/gcaria/camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 596, in rope_rename_refactor
    changes = get_renaming_changes(project, module, offset, new_name, name,
  File "/home/gcaria/camel-snake-pep8/src/camel_snake_pep8/camel_snake_pep8.py", line 564, in get_renaming_changes
    changes = Rename(project, module, offset).get_changes(
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/refactor/rename.py", line 22, in __init__
    self.old_name = worder.get_name_at(self.resource, offset)
  File "/home/gcaria/envs/giacos/lib/python3.8/site-packages/rope/base/worder.py", line 8, in get_name_at
    source_code = resource.read()
AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by abarker** [comment]
An option to accept all changes is something to consider.  There should probably be two cases, one to accept all changes and one to accept all changes without warnings. The default is to accept all changes without warnings, so you can kind of approximate that by just holding down the enter button while the program runs to accept all the changes without warnings.

I pushed out a new version that just prints a warning for that AttributeError.  I'm not sure what it will do in your case because I don't have a way to reproduce the error. It may keep giving the error or may go on to the next renames. I think this is a Rope issue, but I cannot be sure.

If you run the program on a copy of the file `groupMonths.py` alone, does it still give the same error? Anything unusual about the `monthsGroup` variable in the file?

**Comment by gcaria** [comment]
I haven't been able to replicate the problem with `groupMonths.py` myself, so I'm puzzled. At this stage the issue can be closed for what it concerns me.

>The default is to accept all changes without warnings, so you can kind of approximate that by just holding down the enter button while the program runs to accept all the changes without warnings.

I've tried this and only for a few files to modify, it took a long time with the enter button held down, which surely is not very pleasant nor efficient. I could open an issue for this features if you'd like to keep track.

**Comment by abarker** [comment]
I added a couple of command-line options, ``--yes-to-all`` and ``--yes-no-default``.  The first acts as if the user always types 'y', and the latter as if the user just hits enter each time.

**Comment by gcaria** [comment]
That was fast, thanks I'll try them out !

**Comment by gcaria** [comment]
Abusing again this issue to give you my feedback on your great package:

Is there a way to add an option for also editing the import lines ?
I read that `rope` doesn't do this very well, so could this maybe added as an "aggressive" option with appropriate user warnings ?

**Comment by abarker** [comment]
I also finally added a proper `setup.py` and put the package up on PyPI to install with pip.

This program cannot modify names in import statements because it doesn't know any type information from the import statement alone.  It could be a class, a function, a variable, etc., so it is uncertain how to modify it to conform to PEP-8.  That is up to Rope.  When the variable is modified in the original file that it is imported from (assuming that file is in the package), Rope should then change the import.  Sometimes it does, but sometimes it fails to do so.  There's an example where it fails in the `test` directory, when `pkg_dir.pkg_module.py` imports `myVar2` from `pkg_dir.pkg_subdir.subpkg_module`.

**Comment by gcaria** [comment]
Ok, so this is really a Rope issue. Thanks for the explanation, please feel free to close this issue.

**Comment by gcaria** [comment]
Ok, so this is really a Rope issue. Thanks for the explanation, please feel free to close this issue.
